'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Mobile_RequestList

    '''<summary>
    '''frmRequestList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmRequestList As Global.System.Web.UI.MobileControls.Form

    '''<summary>
    '''PageCaption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageCaption As Global.System.Web.UI.MobileControls.Label

    '''<summary>
    '''LnkBack1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkBack1 As Global.System.Web.UI.MobileControls.Link

    '''<summary>
    '''LnkLogOut1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkLogOut1 As Global.System.Web.UI.MobileControls.Link

    '''<summary>
    '''LblBar4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblBar4 As Global.System.Web.UI.MobileControls.Label

    '''<summary>
    '''CmdApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdApprove As Global.System.Web.UI.MobileControls.Command

    '''<summary>
    '''LblBar5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblBar5 As Global.System.Web.UI.MobileControls.Label

    '''<summary>
    '''CmdReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdReject As Global.System.Web.UI.MobileControls.Command

    '''<summary>
    '''LnkFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkFirst As Global.System.Web.UI.MobileControls.Link

    '''<summary>
    '''LblBar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblBar1 As Global.System.Web.UI.MobileControls.Label

    '''<summary>
    '''LnkPrevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkPrevious As Global.System.Web.UI.MobileControls.Link

    '''<summary>
    '''LblBar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblBar2 As Global.System.Web.UI.MobileControls.Label

    '''<summary>
    '''LnkNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkNext As Global.System.Web.UI.MobileControls.Link

    '''<summary>
    '''LblBar3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblBar3 As Global.System.Web.UI.MobileControls.Label

    '''<summary>
    '''LnkLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkLast As Global.System.Web.UI.MobileControls.Link
End Class
