'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Mobile_PTApproval

    '''<summary>
    '''frmPTApprovalEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmPTApprovalEdit As Global.System.Web.UI.MobileControls.Form

    '''<summary>
    '''Link1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Link1 As Global.System.Web.UI.MobileControls.Link

    '''<summary>
    '''Link2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Link2 As Global.System.Web.UI.MobileControls.Link

    '''<summary>
    '''TxtTimesheetNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTimesheetNo As Global.System.Web.UI.MobileControls.TextView

    '''<summary>
    '''TxtDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDate As Global.System.Web.UI.MobileControls.TextView

    '''<summary>
    '''TxtProjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtProjectName As Global.System.Web.UI.MobileControls.TextView

    '''<summary>
    '''TxtFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFromDate As Global.System.Web.UI.MobileControls.TextView

    '''<summary>
    '''TxtToDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtToDate As Global.System.Web.UI.MobileControls.TextView

    '''<summary>
    '''TxtTimesheetDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTimesheetDetails As Global.System.Web.UI.MobileControls.TextView

    '''<summary>
    '''TxtSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtSummary As Global.System.Web.UI.MobileControls.TextView

    '''<summary>
    '''lblComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComment As Global.System.Web.UI.MobileControls.Label

    '''<summary>
    '''txtComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComment As Global.System.Web.UI.MobileControls.TextBox

    '''<summary>
    '''ValidateComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ValidateComment As Global.System.Web.UI.MobileControls.RequiredFieldValidator

    '''<summary>
    '''CmdApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdApprove As Global.System.Web.UI.MobileControls.Command

    '''<summary>
    '''CmdReject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CmdReject As Global.System.Web.UI.MobileControls.Command

    '''<summary>
    '''LnkBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkBack As Global.System.Web.UI.MobileControls.Link

    '''<summary>
    '''LnkLogOut control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LnkLogOut As Global.System.Web.UI.MobileControls.Link
End Class
