'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace PbNIT

    Partial Public Class Login1

        '''<summary>
        '''txtPasswordHide control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPasswordHide As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''Hidden1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Hidden1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
