'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WhizVisualProcessTree

    '''<summary>
    '''frmTree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmTree As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''UltraWebTree1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UltraWebTree1 As Global.Infragistics.WebUI.UltraWebNavigator.UltraWebTree

    '''<summary>
    '''mnuRootMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuRootMenu As Global.Infragistics.WebUI.UltraWebNavigator.UltraWebMenu

    '''<summary>
    '''mnuProcessMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuProcessMenu As Global.Infragistics.WebUI.UltraWebNavigator.UltraWebMenu
End Class
