'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'
'
'    Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace PbNIT

    Partial Public Class MetricsCrossTabGridReport

        '''<summary>
        '''frmCrossTabGridReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmCrossTabGridReport As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''tblGraphs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblGraphs As Global.System.Web.UI.HtmlControls.HtmlTable
    End Class
End Namespace
