'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace PbNIT

    Partial Public Class ProjectMetrics_GetLatestRevision

        '''<summary>
        '''frmMetricRevision control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents frmMetricRevision As Global.System.Web.UI.HtmlControls.HtmlForm
    End Class
End Namespace
