'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PM_QuantitativeObjectives_New

    '''<summary>
    '''frmQuantativeObjectives control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmQuantativeObjectives As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txthidAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthidAction As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txthidData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthidData As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txthidRowCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txthidRowCount As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
